<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Vehicules.aspx.cs" Inherits="Vehicules" %>

<asp:Content ID="ContentCoordonnees" ContentPlaceHolderID="contentPlaceHolderContenu" runat="server">

    <asp:SqlDataSource ID="SqlDataSourceVehicules" runat="server"
        ConnectionString="<%$ ConnectionStrings:ConnectionStringAcharEnLigne2017 %>"
         SelectCommand="SELECT i.[idItem], i.[nomItem], i.[coutAchat], i.[prixVente], i.[imageItem] FROM [item] i INNER JOIN [vehicule] a ON i.[idItem] = a.[idItem]">
    </asp:SqlDataSource>

            <div id="listeproduits">
            <div class="grille">

                <asp:GridView ID="GridViewProduits" runat="server" DataSourceID="SqlDataSourceVehicules" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" AutoGenerateColumns="False" HeaderStyle-CssClass="entetegrille" RowStyle-CssClass="lignesgrille" DataKeyNames="idItem">
                    <Columns>

                        <%-- Colonne du nom de produit dans le GridView --%>
                        <asp:TemplateField HeaderText="Nom" SortExpression="produit_nom">
                            <ItemTemplate>
                                <asp:Label ID="labelNom" runat="server" Text='<%# Eval("nomItem") %>' />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="textBoxNom" runat="server" MaxLength="50" Text='<%# Bind("idItem") %>'/>
                                <asp:RequiredFieldValidator ID="validationNomRequis" runat="server" ControlToValidate="textBoxNom"
                                    ErrorMessage="requis" CssClass="erreurvalidateur" SetFocusOnError="True" ForeColor="Red" ValidationGroup="modif" />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <%-- Colonne du prix du produit dans le GridView --%>
                        <asp:TemplateField HeaderText="Prix" SortExpression="produit_prix">
                            <ItemTemplate>
                                <asp:Label ID="labelPrix" runat="server" Text='<%# Eval("prixVente") %>' Width="100px" />
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="textBoxPrix" runat="server" MaxLength="10" Text='<%# Bind("prixVente", "{0:F2}") %>'/>
                                <asp:RequiredFieldValidator ID="validationPrixRequis" runat="server" ControlToValidate="textBoxPrix"
                                    ErrorMessage="requis" CssClass="erreurvalidateur" SetFocusOnError="True" ForeColor="Red" ValidationGroup="modif" />
                                <asp:CompareValidator ID="CompareValidatorPrix" runat="server" Operator="DataTypeCheck" Type="Double"
                                    ControlToValidate="textBoxPrix" ErrorMessage="La valeur doit être numérique." ForeColor="Red" ValidationGroup="modif" />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <%-- Colonne de l'image du produit dans le GridView --%>
                        <asp:TemplateField HeaderText="Image" SortExpression="prixVente">
                            <ItemTemplate>
                                <asp:Image ID="imageItem" ImageUrl='<%# Eval("imageItem", "~/medias/commun/produits/vehicules/{0}").ToString() %>' runat="server" CssClass="boiteimage" Width="120px"/>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="textBoxImage" runat="server" MaxLength="50" Text='<%# Bind("imageItem") %>'/>
                                <asp:RequiredFieldValidator ID="validationImageRequis" runat="server" ControlToValidate="textBoxImage"
                                    ErrorMessage="requis" CssClass="erreurvalidateur" SetFocusOnError="True" ForeColor="Red" ValidationGroup="modif" />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <%-- Colonne du nombre d'item a ajouter au panier dans le GridView --%>
                        <asp:TemplateField HeaderText="Ajout panier" SortExpression="prixVente">
                            <ItemTemplate>
                                <asp:TextBox ID="textBoxQte" TextMode="Number" runat="server" Text="0" class="textboxform" min="0" max="999" step="1" Width="50px"/>
                                <asp:Button ID="buttonAddPanier" runat="server" Text="Ajouter Panier" OnClick="buttonAddPanier_Click"></asp:Button>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                     </Columns>
                     <EmptyDataTemplate>
                        <asp:Label ID="labelCategorieVide" runat="server" Text="Il n'y a aucun accesoire correspondant à la catégorie sélectionnée." CssClass="classeMessage" />
                     </EmptyDataTemplate>
                </asp:GridView>
                <asp:Label ID="labelMessage" runat="server" ForeColor="Red" CssClass="textemargin" />
            </div>
        </div>

</asp:Content>
